parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     jeremyblog
    database_user:     root
    database_password: root

    mailer_transport: "gmail"
    mailer_encryption: "ssl"
    mailer_auth_mode: "login"
    mailer_host: "smtp.gmail.com"
    mailer_user: "jeremyistesting"
    mailer_password: "chenfeng999"

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
